# Generated by Django 2.0.1 on 2018-01-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'That name is taken, sorry!. Try another one.'}, max_length=90, unique=True)),
                ('delegate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_of', to='auth.Permission')),
                ('perms', models.ManyToManyField(related_name='in_roles', to='auth.Permission')),
            ],
        ),
    ]
